@echo off
REM ****************************************************************************
REM Vivado (TM) v2017.4 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Feb 23 10:57:07 +0100 2018
REM SW Build 2086221 on Fri Dec 15 20:55:39 MST 2017
REM
REM Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim tb_forward_elimination_behav -key {Behavioral:sim_1:Functional:tb_forward_elimination} -tclbatch tb_forward_elimination.tcl -view E:/One Drive/OneDrive for Business/NTNU/Master/Anomaly-detection/FPGA_implementation/Anomaly_detection/corr_tb_behav.wcfg -view E:/One Drive/OneDrive for Business/NTNU/Master/Anomaly-detection/FPGA_implementation/Anomaly_detection/corr_tb_behav1.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
